"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { 
  FileText, 
  Download, 
  PieChart as PieChartIcon, 
  Calendar, 
  AlertCircle,
  TrendingUp,
  BarChart2
} from "lucide-react"

const reportTypes = [
  { title: "Inventory Audit", description: "Complete list of all books with valuation and condition.", icon: BarChart2, color: "text-blue-600" },
  { title: "Overdue Summary", description: "Critical list of members with outstanding books.", icon: AlertCircle, color: "text-rose-600" },
  { title: "Lending History", description: "Monthly breakdown of all borrowing transactions.", icon: TrendingUp, color: "text-emerald-600" },
  { title: "Member Growth", description: "New membership registrations over the last quarter.", icon: Calendar, color: "text-orange-600" },
]

export default function ReportsPage() {
  return (
    <div className="space-y-8 animate-in-up">
      <div>
        <h1 className="text-3xl font-bold font-headline text-primary">Reporting Portal</h1>
        <p className="text-muted-foreground mt-1">Generate and export system-wide performance reports.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reportTypes.map((report, i) => (
          <Card key={i} className="group hover:shadow-lg transition-all border-none shadow-sm overflow-hidden flex flex-col">
            <div className="h-1 bg-muted group-hover:bg-secondary transition-colors" />
            <CardHeader className="flex flex-row items-start justify-between pb-2">
              <div className="space-y-1">
                <CardTitle className="text-xl font-headline font-bold flex items-center gap-2">
                  <report.icon className={cn("w-5 h-5", report.color)} />
                  {report.title}
                </CardTitle>
                <p className="text-sm text-muted-foreground">{report.description}</p>
              </div>
            </CardHeader>
            <CardContent className="mt-auto pt-6 flex justify-between items-center border-t">
              <span className="text-[10px] uppercase font-bold text-muted-foreground tracking-widest">Last updated: 2h ago</span>
              <Button size="sm" className="bg-primary gap-2">
                <Download className="w-4 h-4" />
                Generate PDF
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card className="border-none shadow-sm">
        <CardHeader>
          <CardTitle className="font-headline font-bold">Recent Exports</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {[1, 2, 3].map((_, i) => (
              <div key={i} className="flex items-center justify-between p-4 bg-muted/20 rounded-xl border border-dashed hover:border-secondary/50 transition-colors">
                <div className="flex items-center gap-4">
                  <div className="bg-white p-2 rounded-lg border shadow-sm">
                    <FileText className="w-5 h-5 text-secondary" />
                  </div>
                  <div>
                    <h4 className="font-medium text-primary">Monthly_Audit_Oct_2024.pdf</h4>
                    <p className="text-xs text-muted-foreground">Generated by Admin User • Oct 31, 2024</p>
                  </div>
                </div>
                <Button variant="ghost" size="sm" className="text-secondary hover:text-secondary hover:bg-secondary/10">
                  Download
                </Button>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

function cn(...inputs: any[]) {
  return inputs.filter(Boolean).join(' ')
}